---
title: "Final Project"
author: "Cypress Marrs, Briana Cervantes"
date: "12/3/2021"
output:
  html_document:
    toc: true 
    toc_float: true 
    toc_depth: 6
    theme: yeti
    highlight: textmate
    code_folding: "hide"
    css: style.css
editor_options: 
  markdown: 
    wrap: 72
---
```{r initial, include=FALSE, warning=FALSE, message=FALSE}
# Libraries -----------------
library(tidyr)
library(dplyr)
library(lubridate)
library(sf)
library(tidycensus)
library(tidyverse)
library(tigris)
library(riem)
library(gridExtra)
library(knitr)
library(kableExtra)
library(caret)
library(knitr) 
library(pscl)
library(plotROC)
library(gtsummary) #for table cause broom always f's everything up
library(pROC)
library(tibble)
library(cowplot)
## FOR MAPS ~~
library(RColorBrewer)
library(ggmap)  
library(maps)
library(mapdata)



options(tigris_class = "sf")
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")


palette6 <- c("#260a03", "#a81010", "#f8cd12", "#f2fdff", "#93afdc", "#0c0e1d" )

palette5 <- c("#260a03", "#a81010", "#f8cd12", "#f2fdff", "#93afdc", "#0c0e1d" )

palette4 <- c("#a81010", "#f8cd12", "#93afdc", "#0c0e1d" )

palette3 <- c("#a81010", "#f8cd12", "#93afdc")

palette2 <- c("#260a03", "#a81010")

palette2b <- c( "#260a03", "#f8cd12")

plotTheme2 <-function(base_size = 12, title_size = 18) {
  theme(
    panel.background =element_blank(), 
    text = element_text( color = "#0c0e1d", family="Helvetica"),
    plot.title = element_text(size = title_size, colour = "#0c0e1d", family="Helvetica", face="bold"), 
    plot.subtitle = element_text(face="italic", family="Helvetica", colour = "#0c0e1d"),
    plot.caption = element_text(hjust=0, colour = "#0c0e1d", family="Helvetica"),

    axis.ticks.y = element_line(color = "grey80", size = 0.1),
    plot.background =element_blank(),
    
    panel.grid.major.x   = element_line("grey80", size =0.1 ),
    panel.grid.major.y   =element_line("grey80", size = 0.05),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "#93afdc", fill=NA, size=4),
    #panel.spacing = unit(c(2,2,2,2), "cm"),
    strip.background = element_rect(fill = "#93afdc", color = "#93afdc"),
    strip.text = element_text(size=12,color ="#0c0e1d", family="Helvetica"),
    axis.title = element_text(size=12, color ="#0c0e1d", family="Helvetica",  face="italic"),
    axis.text = element_text(size=10, color ="#0c0e1d", family="Helvetica",),
    
    legend.background = element_blank(),
    legend.title = element_text(colour = "#0c0e1d", face = "italic", family="Helvetica"),
    legend.text = element_text(colour = "#0c0e1d", face = "italic", family="Helvetica"),
    strip.text.x = element_text(size = 14, family="Helvetica", colour = "#0c0e1d")
  )
}


plotTheme3 <-function(base_size = 12, title_size = 18) {
  theme(
    panel.background=element_rect(fill = "#93afdc", color = "#f2fdff"), 
    text = element_text( color = "#0c0e1d", family="Helvetica"),
    plot.title = element_text(size = title_size, colour = "#0c0e1d", family="Helvetica", face="bold"), 
    plot.subtitle = element_text(face="italic", family="Helvetica", colour = "#0c0e1d"),
    plot.caption = element_text(hjust=0, colour = "#0c0e1d", family="Helvetica"),

    axis.ticks.y = element_line(color = "grey80", size = 0.1),
    plot.background =element_blank(),
    
    panel.grid.major.x   = element_line("grey80", size =0.1 ),
    panel.grid.major.y   =element_line("grey80", size = 0.05),
    panel.grid.minor = element_blank(),
    panel.border =element_blank(),
    #panel.spacing = unit(c(2,2,2,2), "cm"),
    strip.background = element_rect(fill = "#f2fdff", color = "#f2fdff"),
    strip.text = element_text(size=12,color ="#0c0e1d", family="Helvetica"),
    axis.title = element_text(size=12, color ="#0c0e1d", family="Helvetica",  face="italic"),
    axis.text = element_text(size=10, color ="#0c0e1d", family="Helvetica",),
    
    legend.background = element_blank(),
    legend.title = element_text(colour = "#0c0e1d", face = "italic", family="Helvetica"),
    legend.text = element_text(colour = "#0c0e1d", face = "italic", family="Helvetica"),
    strip.text.x = element_text(size = 14, family="Helvetica", colour = "#f2fdff")
  )
}



mapTheme2<-function(base_size = 12, title_size = 16) {
  theme(
    text = element_text( color = "#0c0e1d", family="Helvetica"),
    plot.title = element_text(size = title_size,colour = "#0c0e1d", family="Helvetica"),
    plot.subtitle=element_text(face="italic", family="Helvetica"),
    plot.caption=element_text(hjust=0),
    axis.ticks = element_blank(),
    panel.background = element_blank(),axis.title = element_blank(),
    axis.text = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(colour = "#93afdc", fill=NA, size=2),
    strip.text.x = element_text(size = 14, color="#0c0e1d", family="Helvetica"),
    strip.background  = element_rect(fill="#93afdc", color="#93afdc"))
}

```
```{r rawdata,  warning=FALSE, message=FALSE, include=FALSE, echo=TRUE, results='hide'}
# Data -----------
root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
jan2019 <- read.csv("https://raw.githubusercontent.com/bri-ne/MUSA508-Final/main/data/2019_01.csv?token=AVOS24NFX2PEGNUZQUPRNY3BXYPQY")
feb2019 <- read.csv("https://raw.githubusercontent.com/bri-ne/MUSA508-Final/main/data/2019_02.csv?token=AVOS24PUUJDM2PW36N5T6K3BXYPQ4")
mar2019 <- read.csv("https://raw.githubusercontent.com/bri-ne/MUSA508-Final/main/data/2019_03.csv?token=AVOS24MRII4RKEMYGNWWUSDBXYPQ6")
weather.Data <- 
  riem_measures(station = "EWR", date_start = "2019-01-01", date_end = "2019-05-01")
```
```{r wrangledate,  warning=FALSE, message=FALSE, include=FALSE, echo=TRUE, results='hide'}
njtransitdf <- rbind(jan2019, feb2019, mar2019)


njtransitdf <- njtransitdf %>% 
  mutate(scheduled_time_dt = as_datetime(scheduled_time),
         actual_time_dt = as_datetime(actual_time),
         delay_dt = seconds(as.integer(delay_minutes*60)), 
         intervalhour = floor_date(scheduled_time_dt, unit= "hour"),
         week = week(intervalhour)) %>%
  na.omit(delay_dt)

```
```{r stations,  warning=FALSE, message=FALSE, include=FALSE, echo=TRUE, results='hide'}
stoplocations <- read.csv("https://raw.githubusercontent.com/bri-ne/MUSA508-Final/main/Rail_Stations_of_NJ_Transit.csv?token=AVSVPEVU7X6RXZP3RNOK2CLBW7VZO")

#stoplocations <- stoplocations %>%rename(X = "ï..X")%>%st_as_sf(coords = c("X", "Y"), crs =3424, agr = "constant") 

stoplocations <- stoplocations %>%st_as_sf(coords = c("X", "Y"), crs =3424, agr = "constant") 
```
```{r studypanel, warning=FALSE, message=FALSE, include=FALSE, echo=TRUE, results='hide'}
train.template <- 
  filter(njtransitdf, week %in% c(1: 10)) %>%
  filter(line == "Bergen Co. Line " | line == "Gladstone Branch")%>%
  mutate(train_counter=1)%>%
  group_by(line, intervalhour, from) %>%
  summarize(train_count = sum(train_counter, na.rm=T),
            late = mean(delay_dt))

study.panel <- 
  expand.grid(intervalhour = unique(train.template$intervalhour), 
              from = unique(train.template$from),
              line= unique(train.template$line))
```
```{r trainpanel, warning=FALSE, message=FALSE, include=FALSE, echo=TRUE, results='hide'}
train.panel <- train.template %>%
  right_join(study.panel)
```
```{r weather, warning=FALSE, message=FALSE, include=FALSE, echo=TRUE, results='hide'}
weather.Panel <-  
  weather.Data %>%
    mutate_if(is.character, list(~replace(as.character(.), is.na(.), "0"))) %>% 
    replace(is.na(.), 0) %>%
    mutate(intervalhour = ymd_h(substr(valid, 1, 13))) %>%
    mutate(dotw = wday(intervalhour, label=TRUE)) %>%
    group_by(intervalhour) %>%
    summarize(Temperature = max(tmpf),
              Percipitation = sum(p01i),
              Wind_Speed = max(sknt)) %>%
    mutate(Temperature = ifelse(Temperature == 0, 42, Temperature)) 

train.weather.panel <- merge(x=train.panel, y= weather.Panel, by= 'intervalhour', all.x= T)

```

```{r fixna, warning=FALSE, message=FALSE, include=FALSE, echo=TRUE, results='hide'}

train.weather.panel[c("late","train_count")][is.na(train.weather.panel[c("late","train_count")])] <- 0 

```
```{r buildingtimelags, warning=FALSE, message=FALSE, include=FALSE, echo=TRUE, results='hide'}
lag.df <- train.weather.panel %>%
  group_by(line, intervalhour) %>%
  summarise(avg_late = mean(late),
            total_departures = sum(train_count),
            Temperature = mean(Temperature), 
            Percipitation = mean(Percipitation),
            Wind_Speed = mean(Wind_Speed)) %>%
  mutate(lag2Hours = dplyr::lag(avg_late,2),
         lag3Hours = dplyr::lag(avg_late,3),
         lag4Hours = dplyr::lag(avg_late,4),
         lag12Hours = dplyr::lag(avg_late,12),
         lag1day = dplyr::lag(avg_late,24),
         lag1week = dplyr::lag(avg_late, 168), 
         sqrtlag2Hours = sqrt(lag2Hours),
         sqrtlag3Hours = sqrt(lag3Hours),
         sqrtlag4Hours = sqrt(lag4Hours),
         sqrtlag12Hours = sqrt(lag12Hours),
         sqrtlag1day = sqrt(lag1day),
         sqrtlag1week = sqrt(lag1week),
         sqrtlag2hourstotal_departures = sqrt(dplyr::lag(total_departures)),
         lag2Hourswind = dplyr::lag(Wind_Speed,2),
         lag3Hourswind = dplyr::lag(Wind_Speed,3),
         lag4Hourswind = dplyr::lag(Wind_Speed,4),
         lag12Hourswind = dplyr::lag(Wind_Speed,12),
         lag3Hourstemp = dplyr::lag(Temperature,3),
        lag3HoursPercipitation = dplyr::lag(Percipitation,3))

train.weather.panel.lags = merge(train.weather.panel, lag.df, by=c("line", "intervalhour"))

train.weather.panel.lags[c("lag2Hours","lag3Hours","lag4Hours", "lag12Hours", "lag1day", "lag1week",
                           "sqrtlag2Hours", "sqrtlag3Hours", "sqrtlag4Hours", "sqrtlag12Hours", "sqrtlag1day", "sqrtlag1week", "sqrtlag2hourstotal_departures", "lag2Hourswind", "lag3Hourswind", "lag4Hourswind", "lag12Hourswind", "lag3Hourstemp", "lag3HoursPercipitation")][is.na(train.weather.panel.lags[c("lag2Hours","lag3Hours","lag4Hours", "lag12Hours", "lag1day", "lag1week", "sqrtlag2Hours", "sqrtlag3Hours", "sqrtlag4Hours", "sqrtlag12Hours", "sqrtlag1day", "sqrtlag1week", "sqrtlag2hourstotal_departures", "lag2Hourswind", "lag3Hourswind", "lag4Hourswind", "lag12Hourswind", "lag3Hourstemp", "lag3HoursPercipitation")])] <- 0 

```

```{r spacelags, warning=FALSE, message=FALSE, include=FALSE, echo=TRUE, results='hide'}
stoplag<- njtransitdf %>%
 filter(week %in% c(1: 10)) %>%
 filter(line == "Bergen Co. Line " | line == "Gladstone Branch")%>%
 group_by(line, train_id)%>%arrange(stop_sequence)%>%
  mutate(onestoplag = dplyr::lag(delay_minutes),
         twostoplag = dplyr::lag(delay_minutes,2)) %>%
  ungroup() %>%
  group_by(line, from, intervalhour) %>%
  summarise(onestoplag = mean(onestoplag), twostoplag=mean(twostoplag)) %>%
  mutate(onestopearlieron = dplyr::lag(onestoplag,1), twostopearlieron = dplyr::lag(twostoplag,2))%>%
  dplyr::select(intervalhour, line, from, onestoplag, twostoplag, onestopearlieron, twostopearlieron) 

stoplag[c("onestoplag", "twostoplag", "onestopearlieron", "twostopearlieron")][is.na(stoplag[c("onestoplag", "twostoplag", "onestopearlieron", "twostopearlieron")])] <- 0

train.weather.panel.lags.final <- left_join(train.weather.panel.lags, stoplag, by=c("line", "intervalhour", "from"))
```
```{r corrplots, warning=FALSE, message=FALSE, include=FALSE, echo=TRUE, results='hide'}
library(ggcorrplot)

numericVars <- 
  select_if(train.weather.panel.lags.final, is.numeric) %>% na.omit()

corrplot <- ggcorrplot( 
  round(cor(numericVars), 1), 
  p.mat = cor_pmat(numericVars),
  colors = c("#260a03", "white", "#a81010"),
  type="lower",
  insig = "blank") +  
    labs(title = "Correlation Across Numeric Variables") 
corrplot
```

```{r harmonizestationnames, warning=FALSE, message=FALSE, include=FALSE, echo=TRUE, results='hide'}

  ## First, merge with stop data:
  

station_id <- unique(stoplocations$STATION_ID)

  ### Getting the names the same 
      
      ## GLAD ~~~~

train.weather.panel.lags.final$from<-replace(train.weather.panel.lags.final$from, train.weather.panel.lags.final$from == "Hoboken", "Hoboken Terminal")
train.weather.panel.lags.final$to<-replace(train.weather.panel.lags.final$to, train.weather.panel.lags.final$to == "Hoboken", "Hoboken Terminal")

train.weather.panel.lags.final$from<-replace(train.weather.panel.lags.final$from, train.weather.panel.lags.final$from == "Secaucus Upper Lvl", "Secaucus Junction Upper Level")
train.weather.panel.lags.final$to<-replace(train.weather.panel.lags.final$to, train.weather.panel.lags.final$to == "Secaucus Upper Lvl", "Secaucus Junction Upper Level")

stoplocations <- stoplocations%>%mutate(STATION_ID = ifelse(COUNTY == "Orange, NY" & STATION_ID == "Middletown", "Middletown NY", STATION_ID))

train.weather.panel.lags.final$from<-replace(train.weather.panel.lags.final$from, train.weather.panel.lags.final$from == "Broadway Fair Lawn", "Broadway")
train.weather.panel.lags.final$from<-replace(train.weather.panel.lags.final$from, train.weather.panel.lags.final$from == "Glen Rock Boro Hall", "Glen Rock-Boro Hall")
train.weather.panel.lags.final$from<-replace(train.weather.panel.lags.final$from, train.weather.panel.lags.final$from == "Hoboken", "Hoboken Terminal")
train.weather.panel.lags.final$from<-replace(train.weather.panel.lags.final$from, train.weather.panel.lags.final$from == "Radburn Fair Lawn", "Radburn")
train.weather.panel.lags.final$from<-replace(train.weather.panel.lags.final$from, train.weather.panel.lags.final$from == "Ramsey Main St", "Ramsey")
train.weather.panel.lags.final$from<-replace(train.weather.panel.lags.final$from, train.weather.panel.lags.final$from == "Ramsey Route 17", "Rte 17 Ramsey")
train.weather.panel.lags.final$from<-replace(train.weather.panel.lags.final$from, train.weather.panel.lags.final$from == "Secaucus Lower Lvl", "Secaucus Junction Lower Level")


train.weather.panel.lags.final$to<-replace(train.weather.panel.lags.final$to, train.weather.panel.lags.final$to == "Broadway Fair Lawn", "Broadway")
train.weather.panel.lags.final$to<-replace(train.weather.panel.lags.final$to, train.weather.panel.lags.final$to == "Glen Rock Boro Hall", "Glen Rock-Boro Hall")
train.weather.panel.lags.final$to<-replace(train.weather.panel.lags.final$to, train.weather.panel.lags.final$to == "Hoboken", "Hoboken Terminal")
train.weather.panel.lags.final$to<-replace(train.weather.panel.lags.final$to, train.weather.panel.lags.final$to == "Radburn Fair Lawn", "Radburn")
train.weather.panel.lags.final$to<-replace(train.weather.panel.lags.final$to, train.weather.panel.lags.final$to == "Ramsey Main St", "Ramsey")
train.weather.panel.lags.final$to<-replace(train.weather.panel.lags.final$to, train.weather.panel.lags.final$to == "Ramsey Route 17", "Rte 17 Ramsey")
train.weather.panel.lags.final$to<-replace(train.weather.panel.lags.final$to, train.weather.panel.lags.final$to == "Secaucus Lower Lvl", "Secaucus Junction Lower Level")

panelnoGEOM <- train.weather.panel.lags.final %>%
  mutate(STATION_ID = from) %>%
  dplyr::select(-from)

panelGEOM <- left_join(panelnoGEOM, stoplocations) %>%
  st_as_sf(crs =3424, agr = "constant")

```

```{r finalsetup, warning=FALSE, message=FALSE, include=FALSE, echo=TRUE, results='hide'}
panelnoGEOM <- panelnoGEOM %>% 
  mutate(y2_numeric = ifelse(late < minutes(2), 0, 1),
         y2 = ifelse(late < minutes(2), "no", "yes"),
         lateM = late/60,
         hour= hour(intervalhour),
         daynumeric= wday(intervalhour),
         week = week(intervalhour),
         weekday = weekdays(intervalhour),
         y5_numeric = ifelse(late < minutes(5), 0, 1),
         y5 = ifelse(late < minutes(5), "no", "yes"),
         tuesWed.binary = ifelse(weekday == "Tuesday"|weekday == "Wednesday", 1, 0),
         toPenn.binary =  ifelse(to == "New York Penn Station", 1, 0),
         friWed.binary = ifelse(weekday == "Friday"|weekday == "Wednesday", 1, 0),
         toSigStop = ifelse(to == "Broadway Fair Lawn"| to == "Mahwah" | to == "Ramsey Main St"| to == "Waldwick", 0, 1),
         week_numeric = as.numeric(week))

set.seed(2121)
panelnoGEOMTrain <- filter(panelnoGEOM, week < 2) #### BRI, YOU MUST CHANGE THIS BACK TO A 9 
panelnoGEOMTest <- filter(panelnoGEOM, week >= 9)

```
```{r models}
Model1<- glm(y2_numeric ~ .,
                        data=panelnoGEOMTrain %>% 
                          dplyr::select(y2_numeric,
                                        station_id, 
                                        train_count,
                                        onestoplag,
                                        hour,
                                        weekday, 
                                        lag2Hours,
                                        lag3Hours,
                                        lag4Hours,
                                        lag1week,
                                        lag1day,
                                        toPenn.binary, 
                                        tuesWed.binary, 
                                        friWed.binary,
                                        toSigStop,
                                        onestopearlieron,
                                        twostopearlieron,
                                        sqrtlag2Hours,
                                        sqrtlag3Hours,
                                        sqrtlag4Hours,
                                        sqrtlag1day,
                                        sqrtlag2hourstotal_departures,
                                        sqrtlag1week,
                                        lag4Hourswind),  
                        family="binomial" (link="logit"))


Model2<- glm(y2_numeric ~ .,
                        data=panelnoGEOMTrain %>% 
                          dplyr::select(y2_numeric,
                                        station_id, 
                                         train_count,
                                        onestoplag,
                                        hour,
                                        weekday,
                                        onestopearlieron,
                                        twostopearlieron,
                                        sqrtlag2Hours,
                                        sqrtlag3Hours,
                                        sqrtlag4Hours,
                                        sqrtlag1day,
                                        toPenn.binary, 
                                        tuesWed.binary, 
                                        friWed.binary,
                                        toSigStop,
                                        onestopearlieron,
                                        twostopearlieron,
                                        sqrtlag2hourstotal_departures,
                                        sqrtlag1week,
                                        lag4Hourswind),  
                        family="binomial" (link="logit"))

#model1summary.table <- tbl_regression(Model1, exponentiate = TRUE)

#model2summary.table <- tbl_regression(Model2, exponentiate = TRUE)

#commented these out b/c making the tables melts my computer? 
```
```{r CROSVAL, warning=FALSE, message=FALSE, include=FALSE, echo=TRUE, results='hide'}


#### Cross Validation 

ctrl <- trainControl(method = "cv", number = 100, classProbs=TRUE, summaryFunction=twoClassSummary)

##### Model 1-


Model1.vars <- colnames(panelnoGEOMTrain %>% 
                          dplyr::select(station_id, 
                                        train_count,
                                        onestoplag,
                                        hour,
                                        weekday, 
                                        lag2Hours,
                                        lag3Hours,
                                        lag4Hours,
                                        lag1week,
                                        lag1day,
                                        toPenn.binary, 
                                        tuesWed.binary, 
                                        friWed.binary,
                                        toSigStop,
                                        onestopearlieron,
                                        twostopearlieron,
                                        sqrtlag2Hours,
                                        sqrtlag3Hours,
                                        sqrtlag4Hours,
                                        sqrtlag1day,
                                        sqrtlag2hourstotal_departures,
                                        sqrtlag1week,
                                        lag4Hourswind))

ModelcvFit1 <- caret::train(y2 ~ .,
                        data=panelnoGEOMTrain %>% 
                          dplyr::select(all_of(Model1.vars), y2), na.action = na.pass,
                        method="glm", family="binomial",
                        metric="ROC", trControl = ctrl)
```
```{r crossvalidation2}
Model2.vars <- colnames(panelnoGEOMTrain %>% 
                          dplyr::select(station_id, 
                                        onestopearlieron,
                                        twostopearlieron,
                                        sqrtlag2Hours,
                                        sqrtlag3Hours,
                                        sqrtlag4Hours,
                                        sqrtlag1day,
                                        sqrtlag2hourstotal_departures,
                                        sqrtlag1week,
                                        lag4Hourswind))

ModelcvFit2 <- caret::train(y2 ~ .,
                        data=panelnoGEOMTrain %>% 
                          dplyr::select(all_of(Model2.vars), y2), 
                        method="glm", family="binomial",  na.action = na.pass,
                        metric="ROC", trControl = ctrl)

```
```{r goodnessmetrics}

ModelcvFit1.plot<- dplyr::select(ModelcvFit1$resample, -Resample) %>%
  gather(metric, value) %>%
  left_join(gather(ModelcvFit1$results[2:4], metric, mean)) %>%
  ggplot(aes(value)) + 
  geom_histogram(bins=35, fill = "#93afdc") +
  facet_wrap(~metric) +
  geom_vline(aes(xintercept = mean), colour = "#a81010", linetype = 3, size = 1.5) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x="Goodness of Fit", y="Count", title="Model 1 Goodness of Fit Metrics",
       subtitle = "Across-fold mean reprented as dotted lines",
       caption= " ") +
  plotTheme2()

ModelcvFit2.plot<- dplyr::select(ModelcvFit2$resample, -Resample) %>%
  gather(metric, value) %>%
  left_join(gather(ModelcvFit2$results[2:4], metric, mean)) %>%
  ggplot(aes(value)) + 
  geom_histogram(bins=35, fill = "#93afdc") +
  facet_wrap(~metric) +
  geom_vline(aes(xintercept = mean), colour = "#a81010", linetype = 3, size = 1.5) +
  scale_x_continuous(limits = c(0, 1)) +
  labs(x="Goodness of Fit", y="Count", title="Model 2 Goodness of Fit Metrics",
       subtitle = "Across-fold mean reprented as dotted lines",
       caption= " ") +
  plotTheme2()

model1_model2GOF <- plot_grid(ModelcvFit1.plot, ModelcvFit2.plot, nrow=2, ncol=1) # BRI, deliverable

```

```{r PREDICTIONS1, warning=FALSE, message=FALSE, include=FALSE, echo=TRUE, results='hide'}

### MODELS 
#### Setting up Predictions FOR Weather, Stoplag, and Hourlag -----

    ## Model 1

ModelProbs1 <- data.frame(Outcome = as.factor(panelnoGEOMTest$y2_numeric),
                         Probs = predict(Model1, panelnoGEOMTest %>% dplyr::select(all_of(Model1.vars))
                                         , type="response")) 
### Bri : this is throwing up an error: I think it is because I am testing/training on smaller subsets of the total data--I suspect that you won't run into any issues 
    
## Model 2

ModelProbs2 <- data.frame(Outcome = as.factor(panelnoGEOMTest$y2_numeric),
                         Probs = predict(Model2, panelnoGEOMTest, type="response"))

### Bri : this is throwing up an error: I think it is because I am testing/training on smaller subsets of the total data--I suspect that you won't run into any issues 

    ## MODEL 1 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


 model1plot<- ggplot(ModelProbs1, aes(x = Probs, fill = as.factor(Outcome))) + 
  geom_density() +
  facet_grid(Outcome ~ .) +
  scale_fill_manual(values = palette2) +
  labs(x = "Late Over 2 Mins", y = "Density of probabilities",
       title = "Model 1: Distribution of Predicted Probabilities by Actual Outcome",
       caption= " ") +
  theme(strip.text.x = element_text(size = 18),
        legend.position = "none")+plotTheme2()

 
 ModeltestProbs1.thresholds <- 
  iterateThresholds(data=ModelProbs1, observedClass = Outcome, 
                    predictedProbs = Probs)

ModelProbs1.thresholds<-ModelProbs1.thresholds%>%arrange(Rate_TP,Rate_TN) ## 

gladtestProbs1 <- 
  ModelProbs1 %>%
  mutate(predOutcome  = as.factor(ifelse(ModelProbs1$Probs > ### , 1, 0)))


Modelauc1<-pROC::auc(ModelProbs1$Outcome, ModelProbs1$Probs) #0.7465


Modelroc.1<- ggplot(ModelProbs1, aes(d = as.numeric(Outcome), m = Probs)) +
  geom_roc(n.cuts = 50, labels = FALSE, colour = "#a81010") +
  style_roc(theme = theme_grey) +
  geom_abline(slope = 1, intercept = 0, size = 1.5, color = 'grey') +
  labs(title = "ROC Curve - Model 1", subtitle = paste("AUC:", round(gladauc1[1], digits=3)) )+plotTheme2()

   ## MODEL 2 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


 model2plot<- ggplot(ModelProbs2, aes(x = Probs, fill = as.factor(Outcome))) + 
  geom_density() +
  facet_grid(Outcome ~ .) +
  scale_fill_manual(values = palette2) +
  labs(x = "Late Over 2 Mins", y = "Density of probabilities",
       title = "Model 1: Distribution of Predicted Probabilities by Actual Outcome",
       caption= " ") +
  theme(strip.text.x = element_text(size = 18),
        legend.position = "none")+plotTheme2()

 
 ModeltestProbs2.thresholds <- 
  iterateThresholds(data=ModelProbs2, observedClass = Outcome, 
                    predictedProbs = Probs)

ModelProbs2.thresholds<-ModelProbs2.thresholds%>%arrange(Rate_TP,Rate_TN) ## 

gladtestProbs2 <- 
  ModelProbs2 %>%
  mutate(predOutcome  = as.factor(ifelse(ModelProbs2$Probs > , 1, 0)))


Modelauc2<-pROC::auc(ModelProbs2$Outcome, ModelProbs2$Probs) #0.7465


Modelroc.2<- ggplot(ModelProbs2, aes(d = as.numeric(Outcome), m = Probs)) +
  geom_roc(n.cuts = 50, labels = FALSE, colour = "#a81010") +
  style_roc(theme = theme_grey) +
  geom_abline(slope = 1, intercept = 0, size = 1.5, color = 'grey') +
  labs(title = "ROC Curve - Model 2", subtitle = paste("AUC:", round(gladauc1[1], digits=3)) )+plotTheme2()

```
## Visuals --- SOME OLD SOME STILL USEFUL

```{r resultsbar}


gladthresh <- gladtestProbs5.thresholds%>%filter(Threshold == .47)%>%dplyr::select(contains("Rate"), Accuracy)%>%mutate(line="Gladstone Branch") %>%gather(Variable, Value, -line)

bergthresh<- bergtestProbs4.thresholds%>%filter(Threshold == .56)%>%dplyr::select(contains("Rate"), Accuracy)%>%mutate(line="Bergen Co. Line") %>%gather(Variable, Value, -line)

gladbergthresh<-rbind(gladthresh, bergthresh)


resutlsbar <- gladbergthresh%>%
    ggplot(aes(Variable, Value, fill = line), colour= "white") +
      geom_bar(aes(fill = line), position = "dodge", stat = "identity") +
      scale_fill_manual(values = palette2b) +
      labs(title="Model Results",
           #subtitle = " ", 
           x = "Outcome",y = "Rate") +
      plotTheme2() + theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "bottom") 

resultsbar


```
